# Generated by Django 5.2.5 on 2026-04-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationresult',
            options={'verbose_name': 'Calculation Result', 'verbose_name_plural': 'Calculation Results'},
        ),
        migrations.AlterModelOptions(
            name='emergyreference',
            options={'verbose_name': 'Emergy Reference', 'verbose_name_plural': 'Emergy References'},
        ),
        migrations.AlterModelOptions(
            name='importlog',
            options={'verbose_name': 'Import Log', 'verbose_name_plural': 'Import Logs'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
