# Generated by Django 5.2.5 on 2026-04-25 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_alter_userprofile_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution'),
        ),
    ]
