# Generated by Django 6.0.3 on 2026-05-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
